# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.3-mc26.1
maven_group=com.nettakrim.insoluble_concrete
archives_base_name=insoluble_concrete

# Dependencies
fabric_api_version=0.145.1+26.1